print_variables:
	echo GCP_PROJECT_ID:${GCP_PROJECT_ID}
	echo BQ_DATASET:${BQ_DATASET}

# bq_load:
# 	bq load --source_format="CSV" --autodetect --replace ${GCP_PROJECT_ID}:${BQ_DATASET}.inventory data/inventory.csv
# 	bq load --source_format="CSV" --autodetect --replace ${GCP_PROJECT_ID}:${BQ_DATASET}.orders    data/orders.csv
